package com.hys.controltrabajos;

import android.app.*; import android.os.Bundle; import android.content.*; import android.graphics.*; import android.graphics.drawable.*; import android.speech.RecognizerIntent; import android.view.*; import android.widget.*; import java.io.OutputStream; import java.text.*; import java.util.*; import org.json.*;

public class MainActivity extends Activity {
 private static final int VOICE=20,SAVE=21; private final ArrayList<Job> jobs=new ArrayList<>(); private LinearLayout list; private TextView total; private SharedPreferences prefs; private EditText voiceTarget; private final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("es","MX"));
 static class Job {String date,area,work,status;double amount;Job(String d,String a,String w,double m,String s){date=d;area=a;work=w;amount=m;status=s;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("hys_jobs",MODE_PRIVATE);load();showMain();}
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(25,48,86));v.setPadding(dp(4),dp(4),dp(4),dp(4));return v;}
 private GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;} private GradientDrawable stroked(int color,int radius,int stroke){GradientDrawable g=bg(color,radius);g.setStroke(dp(1),stroke);return g;}
 private Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setTypeface(null,1);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setPadding(dp(7),0,dp(7),0);b.setBackground(bg(color,14));return b;}
 private ImageView logo(){ImageView v=new ImageView(this);v.setImageResource(R.drawable.hys_logo);v.setScaleType(ImageView.ScaleType.CENTER_INSIDE);v.setAdjustViewBounds(true);v.setContentDescription("HyS Tecnologías");return v;}
 private TextView icon(String glyph,int size){TextView v=text(glyph,size);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT_BOLD);v.setTextColor(Color.rgb(20,91,180));return v;}
 private void showMain(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(Color.WHITE);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(20),dp(20),dp(30));sc.addView(root);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button menu=button("☰",Color.TRANSPARENT);menu.setTextColor(Color.rgb(10,48,112));menu.setTextSize(27);menu.setBackgroundColor(Color.TRANSPARENT);top.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(52)));Space ts=new Space(this);top.addView(ts,new LinearLayout.LayoutParams(0,1,1));TextView brand=text("HyS",17);brand.setTypeface(null,1);brand.setTextColor(Color.rgb(10,48,112));top.addView(brand);root.addView(top);
  LinearLayout logoCard=new LinearLayout(this);logoCard.setGravity(Gravity.CENTER);logoCard.setPadding(dp(12),dp(7),dp(12),dp(7));logoCard.setBackground(stroked(Color.rgb(247,251,255),20,Color.rgb(205,226,248)));logoCard.addView(logo(),new LinearLayout.LayoutParams(-1,dp(180)));root.addView(logoCard);
  TextView section=text("Control de Trabajos",28);section.setTypeface(null,1);section.setGravity(Gravity.CENTER);section.setTextColor(Color.rgb(10,48,112));section.setPadding(dp(2),dp(22),dp(2),dp(3));root.addView(section);View line=new View(this);line.setBackgroundColor(Color.rgb(30,136,229));LinearLayout.LayoutParams linelp=new LinearLayout.LayoutParams(dp(55),dp(3));linelp.gravity=Gravity.CENTER;linelp.bottomMargin=dp(8);root.addView(line,linelp);TextView sub=text("ORGANIZA  •  REGISTRA  •  DA SEGUIMIENTO",12);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.rgb(111,135,174));sub.setPadding(0,0,0,dp(16));root.addView(sub);
  LinearLayout actions=new LinearLayout(this);Button add=button("＋  NUEVO TRABAJO",Color.rgb(10,112,232)),exp=button("W  EXPORTAR WORD",Color.rgb(111,158,211));actions.addView(add,new LinearLayout.LayoutParams(0,dp(60),1));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,dp(60),1);ep.leftMargin=dp(10);actions.addView(exp,ep);root.addView(actions);
  LinearLayout totalCard=new LinearLayout(this);totalCard.setOrientation(LinearLayout.VERTICAL);totalCard.setPadding(dp(18),dp(13),dp(18),dp(14));totalCard.setBackground(stroked(Color.rgb(246,250,255),18,Color.rgb(205,226,248)));LinearLayout.LayoutParams tcp=new LinearLayout.LayoutParams(-1,-2);tcp.topMargin=dp(18);root.addView(totalCard,tcp);TextView lab=text("TOTAL FACTURABLE (TERMINADOS)",13);lab.setTypeface(null,1);lab.setTextColor(Color.rgb(75,103,150));totalCard.addView(lab);total=text("",29);total.setTypeface(null,1);total.setTextColor(Color.rgb(12,62,170));totalCard.addView(total);
  list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(18);root.addView(list,lp);setContentView(sc);menu.setOnClickListener(v->showMenu());add.setOnClickListener(v->editJob(-1));exp.setOnClickListener(v->exportRtf());render();}
 private void render(){list.removeAllViews();double sum=0;for(int i=0;i<jobs.size();i++){Job j=jobs.get(i);if("Terminado".equals(j.status))sum+=j.amount;final int p=i;LinearLayout c=jobCard(j,p);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=dp(12);list.addView(c,cp);}total.setText(money.format(sum));if(jobs.isEmpty()){TextView ic=icon("✓",44);ic.setPadding(0,dp(24),0,dp(5));list.addView(ic);TextView empty=text("Aún no tienes trabajos registrados",18);empty.setTypeface(null,1);empty.setGravity(Gravity.CENTER);empty.setTextColor(Color.rgb(53,79,119));list.addView(empty);TextView hint=text("Presiona “Nuevo Trabajo” para comenzar",15);hint.setGravity(Gravity.CENTER);hint.setTextColor(Color.rgb(115,137,172));hint.setPadding(0,dp(4),0,dp(22));list.addView(hint);TextView motto=text("—   TECNOLOGÍA  •  SERVICIO  •  CONFIANZA   —",11);motto.setGravity(Gravity.CENTER);motto.setTextColor(Color.rgb(72,111,169));list.addView(motto);}}
 private LinearLayout jobCard(Job j,int p){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(stroked(Color.rgb(248,251,255),16,Color.rgb(220,232,246)));TextView h=text(j.date+"  •  "+j.status,14);h.setTextColor(Color.rgb(80,108,150));c.addView(h);TextView ar=text(j.area,18);ar.setTypeface(null,1);c.addView(ar);c.addView(text(j.work,15));TextView am=text(money.format(j.amount),18);am.setTypeface(null,1);am.setTextColor(Color.rgb(10,91,190));c.addView(am);if(p>=0){LinearLayout x=new LinearLayout(this);Button e=button("Editar",Color.rgb(70,125,190)),s=button("Estado",Color.rgb(49,139,113)),d=button("Eliminar",Color.rgb(185,76,76));x.addView(e,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(46),1);sp.leftMargin=dp(6);x.addView(s,sp);LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(0,dp(46),1);dl.leftMargin=dp(6);x.addView(d,dl);c.addView(x);e.setOnClickListener(v->editJob(p));s.setOnClickListener(v->changeStatus(p));d.setOnClickListener(v->confirmDelete(p));}return c;}
 private void showMenu(){final String[] items={"Inicio","Trabajos actuales","Historial semanal","Buscar trabajo","Exportar reporte Word","Configuración","Acerca de"};new AlertDialog.Builder(this).setTitle("HyS Control de Trabajos").setItems(items,(d,w)->{if(w==0||w==1)showMain();else if(w==2)showWeekly();else if(w==3)showSearch();else if(w==4)exportRtf();else if(w==5)showSettings();else showAbout();}).show();}
 private void page(String title,LinearLayout body){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(28));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",Color.rgb(10,112,232));back.setTextSize(26);bar.addView(back,new LinearLayout.LayoutParams(dp(50),dp(48)));TextView t=text(title,22);t.setTypeface(null,1);t.setTextColor(Color.rgb(10,48,112));LinearLayout.LayoutParams tl=new LinearLayout.LayoutParams(0,-2,1);tl.leftMargin=dp(10);bar.addView(t,tl);root.addView(bar);root.addView(body);sc.addView(root);setContentView(sc);back.setOnClickListener(v->showMain());}
 private Date parseDate(String s){try{return new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).parse(s);}catch(Exception e){return null;}}
 private String weekKey(Job j){Date d=parseDate(j.date);if(d==null)return "Sin fecha";Calendar c=Calendar.getInstance();c.setFirstDayOfWeek(Calendar.MONDAY);c.setTime(d);c.set(Calendar.DAY_OF_WEEK,Calendar.MONDAY);Date a=c.getTime();c.add(Calendar.DAY_OF_MONTH,6);Date z=c.getTime();SimpleDateFormat f=new SimpleDateFormat("dd MMM",new Locale("es","MX"));SimpleDateFormat fy=new SimpleDateFormat("yyyy",Locale.US);return "Semana "+f.format(a)+" – "+f.format(z)+" "+fy.format(z);}
 private void showWeekly(){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);LinkedHashMap<String,ArrayList<Job>> m=new LinkedHashMap<>();for(Job j:jobs){String k=weekKey(j);if(!m.containsKey(k))m.put(k,new ArrayList<>());m.get(k).add(j);}if(m.isEmpty()){TextView e=text("Todavía no hay semanas registradas.",17);e.setGravity(Gravity.CENTER);e.setPadding(0,dp(40),0,0);body.addView(e);}for(String k:m.keySet()){ArrayList<Job> js=m.get(k);double s=0;for(Job j:js)if("Terminado".equals(j.status))s+=j.amount;Button b=button(k+"\n"+js.size()+" trabajos  •  "+money.format(s),Color.rgb(238,246,255));b.setTextColor(Color.rgb(20,62,120));b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(78));p.bottomMargin=dp(10);body.addView(b,p);b.setOnClickListener(v->showWeek(k,js));}page("Historial semanal",body);}
 private void showWeek(String k,ArrayList<Job> js){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);double s=0;for(Job j:js)if("Terminado".equals(j.status))s+=j.amount;TextView sum=text("Total facturado\n"+money.format(s),25);sum.setTypeface(null,1);sum.setTextColor(Color.rgb(12,62,170));sum.setPadding(dp(12),dp(18),dp(12),dp(18));sum.setBackground(stroked(Color.rgb(246,250,255),16,Color.rgb(205,226,248)));body.addView(sum);for(Job j:js){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(10);body.addView(jobCard(j,-1),p);}Button ex=button("W  EXPORTAR SEMANA A WORD",Color.rgb(10,112,232));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(-1,dp(58));xp.topMargin=dp(18);body.addView(ex,xp);ex.setOnClickListener(v->exportRtf(js,k));page(k,body);}
 private void showSearch(){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);EditText q=input("Buscar por área, trabajo, fecha o estado","");body.addView(q,new LinearLayout.LayoutParams(-1,dp(58)));LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);body.addView(results);q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){results.removeAllViews();String z=s.toString().toLowerCase();if(z.isEmpty())return;for(int i=0;i<jobs.size();i++){Job j=jobs.get(i);if((j.area+" "+j.work+" "+j.date+" "+j.status).toLowerCase().contains(z)){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(10);results.addView(jobCard(j,i),p);}}}public void afterTextChanged(android.text.Editable e){}});page("Buscar trabajo",body);}
 private void showSettings(){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);String[] x={"Moneda: Peso Mexicano (MXN)","Formato de fecha: dd/MM/yyyy","Datos: guardados localmente en este dispositivo","Tema: Claro","Los trabajos se conservan al actualizar la app"};for(String s:x){TextView v=text(s,16);v.setPadding(dp(14),dp(18),dp(14),dp(18));v.setBackground(stroked(Color.rgb(248,251,255),14,Color.rgb(220,232,246)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);body.addView(v,p);}page("Configuración",body);}
 private void showAbout(){new AlertDialog.Builder(this).setTitle("HyS Control de Trabajos").setMessage("Tecnología, servicio y confianza.\n\nControl de trabajos, historial semanal, búsqueda y exportación de reportes.").setPositiveButton("Cerrar",null).show();}
 private EditText input(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextSize(16);return e;} private Button mic(EditText t){Button b=button("Dictar",Color.rgb(70,125,190));b.setOnClickListener(v->{voiceTarget=t;Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"es-MX");try{startActivityForResult(i,VOICE);}catch(Exception e){Toast.makeText(this,"Dictado no disponible",Toast.LENGTH_LONG).show();}});return b;}
 private void editJob(int p){Job old=p>=0?jobs.get(p):null;LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(16),0,dp(16),0);EditText date=input("Fecha",old==null?new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date()):old.date),area=input("Área de trabajo / lugar",old==null?"":old.area),work=input("Trabajo realizado",old==null?"":old.work),amount=input("Importe",old==null?"":String.valueOf(old.amount));work.setMinLines(3);amount.setInputType(2|8192);f.addView(date);f.addView(area);f.addView(work);f.addView(mic(work));f.addView(amount);new AlertDialog.Builder(this).setTitle(p<0?"Nuevo trabajo":"Editar trabajo").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->{String ar=area.getText().toString().trim(),wo=work.getText().toString().trim();if(ar.isEmpty()||wo.isEmpty()){Toast.makeText(this,"Área y trabajo son obligatorios",Toast.LENGTH_LONG).show();return;}double am=0;try{am=Double.parseDouble(amount.getText().toString().replace(",",""));}catch(Exception ignored){}Job n=new Job(date.getText().toString().trim(),ar,wo,am,old==null?"Pendiente":old.status);if(p<0)jobs.add(0,n);else jobs.set(p,n);save();showMain();}).show();}
 private void changeStatus(int p){String[] st={"Pendiente","Terminado","Cancelado"};int ch=Math.max(0,Arrays.asList(st).indexOf(jobs.get(p).status));new AlertDialog.Builder(this).setTitle("Estado").setSingleChoiceItems(st,ch,(d,x)->{jobs.get(p).status=st[x];save();showMain();d.dismiss();}).show();} private void confirmDelete(int p){new AlertDialog.Builder(this).setTitle("Eliminar trabajo").setMessage("¿Deseas eliminar este trabajo?").setNegativeButton("No",null).setPositiveButton("Sí",(d,w)->{jobs.remove(p);save();showMain();}).show();}
 private void save(){JSONArray a=new JSONArray();try{for(Job j:jobs){JSONObject o=new JSONObject();o.put("date",j.date);o.put("area",j.area);o.put("work",j.work);o.put("amount",j.amount);o.put("status",j.status);a.put(o);}}catch(Exception ignored){}prefs.edit().putString("jobs",a.toString()).apply();} private void load(){try{JSONArray a=new JSONArray(prefs.getString("jobs","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);jobs.add(new Job(o.optString("date"),o.optString("area"),o.optString("work"),o.optDouble("amount"),o.optString("status","Pendiente")));}}catch(Exception ignored){}}
 private String esc(String s){return s.replace("\\","\\\\").replace("{","\\{").replace("}","\\}").replace("\n","\\line ");} private String today(){return new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date());}
 private String rtf(Collection<Job> source){StringBuilder b=new StringBuilder("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\fs24 ");b.append("\\b HyS Tecnologias - Control de Trabajos\\b0\\par Fecha del reporte: ").append(today()).append("\\par Tecnologia, servicio y confianza. - S.D.G. - Proverbios 1:7\\par\\par ");double sum=0;for(Job j:source)if("Terminado".equals(j.status)){sum+=j.amount;b.append("\\bullet ").append(esc((j.area+" - "+j.work+" - "+money.format(j.amount)).toUpperCase(new Locale("es","MX")))).append("\\par ");}b.append("\\par\\b TOTAL: ").append(esc(money.format(sum))).append("\\b0}");return b.toString();}
 private void exportRtf(){exportRtf(jobs,"Trabajos");} private void exportRtf(Collection<Job> source,String name){pendingExport=new ArrayList<>(source);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/rtf");i.putExtra(Intent.EXTRA_TITLE,name.replace(" ","_")+"_"+new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())+".rtf");startActivityForResult(i,SAVE);} private ArrayList<Job> pendingExport;
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;if(req==VOICE&&voiceTarget!=null){ArrayList<String> r=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(r!=null&&!r.isEmpty()){String before=voiceTarget.getText().toString();voiceTarget.setText(before+(before.isEmpty()?"":" ")+r.get(0));voiceTarget.setSelection(voiceTarget.length());}}else if(req==SAVE){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(rtf(pendingExport==null?jobs:pendingExport).getBytes("UTF-8"));Toast.makeText(this,"Documento guardado",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo guardar",Toast.LENGTH_LONG).show();}}}
 @Override public void onBackPressed(){showMain();}
}
