package com.hys.controltrabajos;

import android.app.*; import android.os.Bundle; import android.content.*; import android.graphics.*; import android.graphics.drawable.*; import android.speech.RecognizerIntent; import android.view.*; import android.widget.*; import java.io.OutputStream; import java.text.*; import java.util.*; import org.json.*;

public class MainActivity extends Activity {
 private static final int VOICE=20,SAVE=21; private final ArrayList<Job> jobs=new ArrayList<>(); private LinearLayout list; private TextView total; private SharedPreferences prefs; private EditText voiceTarget; private final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("es","MX"));
 static class Job {String date,area,work,status;double amount;Job(String d,String a,String w,double m,String s){date=d;area=a;work=w;amount=m;status=s;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("hys_jobs",MODE_PRIVATE);load();showMain();}
 private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(30,30,30));v.setPadding(12,8,12,8);return v;} private Button button(String s){Button b=new Button(this);b.setText(s);return b;}
 private TextView logo(){TextView v=text("H·S",22);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(Color.rgb(13,71,161));v.setBackground(g);return v;}
 private void showMain(){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,20,24,24);sc.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(logo(),new LinearLayout.LayoutParams(88,88));TextView title=text("HyS Tecnologías",26);title.setTextColor(Color.rgb(13,71,161));head.addView(title);root.addView(head);root.addView(text("Tecnología, servicio y confianza.  •  S.D.G.  •  Proverbios 1:7",12));root.addView(text("Control de Trabajos",19));LinearLayout a=new LinearLayout(this);Button add=button("+ NUEVO TRABAJO"),exp=button("EXPORTAR WORD");a.addView(add,new LinearLayout.LayoutParams(0,-2,1));a.addView(exp,new LinearLayout.LayoutParams(0,-2,1));root.addView(a);total=text("",18);root.addView(total);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);setContentView(sc);add.setOnClickListener(v->editJob(-1));exp.setOnClickListener(v->exportRtf());render();}
 private void render(){list.removeAllViews();double sum=0;for(int i=0;i<jobs.size();i++){Job j=jobs.get(i);if("Terminado".equals(j.status))sum+=j.amount;final int p=i;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(10,12,10,12);c.setBackgroundColor(Color.rgb(245,247,250));c.addView(text(j.date+"  •  "+j.status,15));c.addView(text(j.area,17));c.addView(text(j.work,15));c.addView(text(money.format(j.amount),16));LinearLayout x=new LinearLayout(this);Button e=button("Editar"),s=button("Estado"),d=button("Eliminar");x.addView(e,new LinearLayout.LayoutParams(0,-2,1));x.addView(s,new LinearLayout.LayoutParams(0,-2,1));x.addView(d,new LinearLayout.LayoutParams(0,-2,1));c.addView(x);list.addView(c);e.setOnClickListener(v->editJob(p));s.setOnClickListener(v->changeStatus(p));d.setOnClickListener(v->confirmDelete(p));}total.setText("Total facturable (terminados): "+money.format(sum));}
 private EditText input(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextSize(16);return e;} private Button mic(EditText t){Button b=button("🎤 Dictar");b.setOnClickListener(v->{voiceTarget=t;Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"es-MX");try{startActivityForResult(i,VOICE);}catch(Exception e){Toast.makeText(this,"Dictado no disponible",Toast.LENGTH_LONG).show();}});return b;}
 private void editJob(int p){Job old=p>=0?jobs.get(p):null;LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(16,0,16,0);EditText date=input("Fecha",old==null?new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date()):old.date),area=input("Área de trabajo / lugar",old==null?"":old.area),work=input("Trabajo realizado",old==null?"":old.work),amount=input("Importe",old==null?"":String.valueOf(old.amount));work.setMinLines(3);amount.setInputType(2|8192);f.addView(date);f.addView(area);f.addView(work);f.addView(mic(work));f.addView(amount);new AlertDialog.Builder(this).setTitle(p<0?"Nuevo trabajo":"Editar trabajo").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->{String ar=area.getText().toString().trim(),wo=work.getText().toString().trim();if(ar.isEmpty()||wo.isEmpty()){Toast.makeText(this,"Área y trabajo son obligatorios",Toast.LENGTH_LONG).show();return;}double am=0;try{am=Double.parseDouble(amount.getText().toString().replace(",",""));}catch(Exception ignored){}Job n=new Job(date.getText().toString().trim(),ar,wo,am,old==null?"Pendiente":old.status);if(p<0)jobs.add(0,n);else jobs.set(p,n);save();render();}).show();}
 private void changeStatus(int p){String[] st={"Pendiente","Terminado","Cancelado"};int ch=Math.max(0,Arrays.asList(st).indexOf(jobs.get(p).status));new AlertDialog.Builder(this).setTitle("Estado").setSingleChoiceItems(st,ch,(d,x)->{jobs.get(p).status=st[x];save();render();d.dismiss();}).show();} private void confirmDelete(int p){new AlertDialog.Builder(this).setTitle("Eliminar trabajo").setMessage("¿Deseas eliminar este trabajo?").setNegativeButton("No",null).setPositiveButton("Sí",(d,w)->{jobs.remove(p);save();render();}).show();}
 private void save(){JSONArray a=new JSONArray();try{for(Job j:jobs){JSONObject o=new JSONObject();o.put("date",j.date);o.put("area",j.area);o.put("work",j.work);o.put("amount",j.amount);o.put("status",j.status);a.put(o);}}catch(Exception ignored){}prefs.edit().putString("jobs",a.toString()).apply();} private void load(){try{JSONArray a=new JSONArray(prefs.getString("jobs","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);jobs.add(new Job(o.optString("date"),o.optString("area"),o.optString("work"),o.optDouble("amount"),o.optString("status","Pendiente")));}}catch(Exception ignored){}}
 private String esc(String s){return s.replace("\\","\\\\").replace("{","\\{").replace("}","\\}").replace("\n","\\line ");} private String today(){return new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date());}
 private String rtf(){StringBuilder b=new StringBuilder("{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\fs24 ");b.append("\\b HyS Tecnologias - Control de Trabajos\\b0\\par Fecha del reporte: ").append(today()).append("\\par Tecnologia, servicio y confianza. - S.D.G. - Proverbios 1:7\\par\\par ");double sum=0;for(Job j:jobs)if("Terminado".equals(j.status)){sum+=j.amount;b.append("\\bullet ").append(esc((j.area+" - "+j.work+" - "+money.format(j.amount)).toUpperCase(new Locale("es","MX")))).append("\\par ");}b.append("\\par\\b TOTAL: ").append(esc(money.format(sum))).append("\\b0}");return b.toString();}
 private void exportRtf(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/rtf");i.putExtra(Intent.EXTRA_TITLE,"Trabajos_"+new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())+".rtf");startActivityForResult(i,SAVE);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;if(req==VOICE&&voiceTarget!=null){ArrayList<String> r=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(r!=null&&!r.isEmpty()){String before=voiceTarget.getText().toString();voiceTarget.setText(before+(before.isEmpty()?"":" ")+r.get(0));voiceTarget.setSelection(voiceTarget.length());}}else if(req==SAVE){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(rtf().getBytes("UTF-8"));Toast.makeText(this,"Documento guardado",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo guardar",Toast.LENGTH_LONG).show();}}}
}
